# Generated by Django 5.0.14 on 2025-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
