# Generated by Django 5.0.14 on 2025-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название точки')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=255, verbose_name='График работы')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Точка продаж',
                'verbose_name_plural': 'Точки продаж',
            },
        ),
    ]
